{% set required_compiler_version = "2024.0" %}
{% set excluded_compiler_version1 = "2024.0.1" %}
{% set excluded_compiler_version2 = "2024.0.2" %}
{% set max_compiler_version = "2024.1.0a0" %}


package:
    name: foo
    version: 0.0.1

source:
    path: ..

build:
    number: 0

requirements:
    build:
        - {{ compiler('cxx') }}
        - {{ compiler('dpcpp') }} >={{ required_compiler_version }},!={{ excluded_compiler_version1 }},!={{ excluded_compiler_version2 }},<{{ max_compiler_version }}  # [not osx]
        - sysroot_linux-64 >=2.28  # [linux]
    host:
        - python
    run:
        - python
        - dpcpp-cpp-rt >={{ required_compiler_version }},<{{ max_compiler_version }}  # [not osx]
